import os
import uuid
import logging
import sys
import asyncio
from functools import wraps
from flask import Flask, request, jsonify
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types
from agent import root_agent

# Fix emoji issues in Windows Terminal
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8')

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("agent_server.log", encoding='utf-8'),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger("ResearchServer")

app = Flask(__name__)

# ===== AUTHENTICATION CONFIGURATION =====
# Set your API key as environment variable: API_KEY
API_KEY = os.getenv("API_KEY")
REQUIRE_AUTH = os.getenv("REQUIRE_AUTH", "true").lower() == "true"

def require_api_key(f):
    """Decorator to enforce API key authentication"""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not REQUIRE_AUTH:
            return f(*args, **kwargs)
        
        # Check for API key in headers
        provided_key = request.headers.get('X-API-Key') or request.headers.get('Authorization')
        
        # Handle Bearer token format
        if provided_key and provided_key.startswith('Bearer '):
            provided_key = provided_key[7:]
        
        if not provided_key:
            logger.warning("Request without API key")
            return jsonify({
                "status": "error",
                "error": "Missing API key. Provide via X-API-Key or Authorization header"
            }), 401
        
        if provided_key != API_KEY:
            logger.warning("Invalid API key attempt")
            return jsonify({
                "status": "error",
                "error": "Invalid API key"
            }), 403
        
        return f(*args, **kwargs)
    return decorated_function

# Initialize Session Service and Runner once
session_service = InMemorySessionService()
runner = Runner(
    agent=root_agent,
    app_name="research_app", 
    session_service=session_service
)

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint for status monitoring (no auth required)"""
    return jsonify({
        "status": "healthy", 
        "agent": "research_agent",
        "authentication": "enabled" if REQUIRE_AUTH else "disabled"
    }), 200

@app.route('/a2a/task', methods=['POST'])
@require_api_key
def handle_a2a_task():
    """Main research task endpoint (authentication required)"""
    session_id = str(uuid.uuid4())
    user_id = "user_default"
    
    try:
        task_data = request.json
        
        if not task_data:
            return jsonify({
                "status": "error",
                "error": "Request body must be JSON"
            }), 400
        
        query = task_data.get("query")
        
        if not query:
            return jsonify({
                "status": "error",
                "error": "Missing required field: query"
            }), 400
        
        mode = task_data.get("search_mode", "normal")
        domains = task_data.get("domains", [])
        max_results = task_data.get("max_results_per_tool", 10)

        logger.info(f"🚀 Starting | Session: {session_id} | Query: {query}")

        # Create session asynchronously
        asyncio.run(session_service.create_session(
            user_id=user_id,
            session_id=session_id,
            app_name="research_app"
        ))

        # Prepare Prompt
        prompt = f"""Query: {query}
Search Mode: {mode}
Domains: {domains if domains else "None"}
Max Results per Tool: {max_results}"""

        content = types.Content(role="user", parts=[types.Part(text=prompt)])

        final_text_parts = []
        
        # Run agent and collect responses
        for event in runner.run(
            user_id=user_id,
            session_id=session_id,
            new_message=content
        ):
            if hasattr(event, 'text') and event.text:
                final_text_parts.append(event.text)
            elif hasattr(event, 'content') and event.content:
                for part in event.content.parts:
                    if hasattr(part, 'text') and part.text:
                        final_text_parts.append(part.text)

            if event.is_final_response():
                break

        full_report = "".join(final_text_parts).strip()
        
        if not full_report:
            logger.error(f"❌ Empty report generated | Session: {session_id}")
            return jsonify({
                "status": "failed", 
                "error": "No text generated by agent"
            }), 500

        logger.info(f"✅ Success | Session: {session_id}")
        return jsonify({
            "status": "completed", 
            "research_report": full_report,
            "session_id": session_id
        })

    except Exception as e:
        logger.error(f"💥 Error: {str(e)}", exc_info=True)
        return jsonify({
            "status": "failed", 
            "error": str(e)
        }), 500

@app.route('/a2a/info', methods=['GET'])
def agent_info():
    """Endpoint to get agent capabilities and information"""
    from agent import get_agent_card
    return jsonify(get_agent_card()), 200

@app.errorhandler(404)
def not_found(error):
    return jsonify({
        "status": "error",
        "error": "Endpoint not found"
    }), 404

@app.errorhandler(500)
def internal_error(error):
    return jsonify({
        "status": "error",
        "error": "Internal server error"
    }), 500

if __name__ == '__main__':
    # Check for required environment variables
    if REQUIRE_AUTH and not API_KEY:
        logger.error("API_KEY environment variable not set but REQUIRE_AUTH=true")
        sys.exit(1)
    
    port = int(os.getenv("PORT", 5000))
    logger.info(f"Starting server on port {port} (auth={'enabled' if REQUIRE_AUTH else 'disabled'})")
    app.run(host='0.0.0.0', port=port, debug=False)